export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";

export const FETCH_BOOKS_BY_LIBRARY_REQUEST = "FETCH_BOOKS_BY_LIBRARY_REQUEST";
export const FETCH_BOOKS_BY_LIBRARY_SUCCESS = "FETCH_BOOKS_BY_LIBRARY_SUCCESS";
export const FETCH_BOOKS_BY_LIBRARY_FAILURE = "FETCH_BOOKS_BY_LIBRARY_FAILURE";

export const FETCH_ISSUES_SUCCESS = "FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_BY_STUDENT_SUCCESS = "FETCH_ISSUES_BY_STUDENT_SUCCESS";

export const ISSUE_BOOK_SUCCESS = "ISSUE_BOOK_SUCCESS";
export const RETURN_BOOK_SUCCESS = "RETURN_BOOK_SUCCESS";