export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const FETCH_ISSUES_SUCCESS = "FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_BY_STUDENT_SUCCESS = "FETCH_ISSUES_BY_STUDENT_SUCCESS";

export const ISSUE_BOOK_SUCCESS = "ISSUE_BOOK_SUCCESS";
export const RETURN_BOOK_SUCCESS = "RETURN_BOOK_SUCCESS";