export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const FETCH_LIBRARIAN_REQUEST = "FETCH_LIBRARIAN_REQUEST";
export const FETCH_LIBRARIAN_SUCCESS = "FETCH_LIBRARIAN_SUCCESS";
export const FETCH_LIBRARIAN_FAILURE = "FETCH_LIBRARIAN_FAILURE";

export const FETCH_UNIVERSITY_STAFF_REQUEST = "FETCH_UNIVERSITY_STAFF_REQUEST";
export const FETCH_UNIVERSITY_STAFF_SUCCESS = "FETCH_UNIVERSITY_STAFF_SUCCESS";
export const FETCH_UNIVERSITY_STAFF_FAILURE = "FETCH_UNIVERSITY_STAFF_FAILURE";

export const ADD_LIBRARIAN_SUCCESS = "ADD_LIBRARIAN_SUCCESS";