export const FETCH_STUDENT_BOOKS_REQUEST = "FETCH_STUDENT_BOOKS_REQUEST";
export const FETCH_STUDENT_BOOKS_SUCCESS = "FETCH_STUDENT_BOOKS_SUCCESS";
export const FETCH_STUDENT_BOOKS_FAILURE = "FETCH_STUDENT_BOOKS_FAILURE";