export const FETCH_UNIVERSITIES_REQUEST = "FETCH_UNIVERSITIES_REQUEST";
export const FETCH_UNIVERSITIES_SUCCESS = "FETCH_UNIVERSITIES_SUCCESS";
export const FETCH_UNIVERSITIES_FAILURE = "FETCH_UNIVERSITIES_FAILURE";

export const FETCH_MY_UNIVERSITY_REQUEST = "FETCH_MY_UNIVERSITY_REQUEST";
export const FETCH_MY_UNIVERSITY_SUCCESS = "FETCH_MY_UNIVERSITY_SUCCESS";
export const FETCH_MY_UNIVERSITY_FAILURE = "FETCH_MY_UNIVERSITY_FAILURE";

export const UPDATE_UNIVERSITY_REQUEST = "UPDATE_UNIVERSITY_REQUEST";
export const UPDATE_UNIVERSITY_SUCCESS = "UPDATE_UNIVERSITY_SUCCESS";
export const UPDATE_UNIVERSITY_FAILURE = "UPDATE_UNIVERSITY_FAILURE";

export const DELETE_UNIVERSITY_REQUEST = "DELETE_UNIVERSITY_REQUEST";
export const DELETE_UNIVERSITY_SUCCESS = "DELETE_UNIVERSITY_SUCCESS";
export const DELETE_UNIVERSITY_FAILURE = "DELETE_UNIVERSITY_FAILURE";