name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Docker Image to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: library-management-1001
          install_components: 'beta'

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/library-management-1001/library-backend .

      - name: Push Docker image to Container Registry
        run: |
          docker push gcr.io/library-management-1001/library-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy library \
            --image gcr.io/library-management-1001/library-backend \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
